### ISSUE TITLE
screen flickering when mouse move

### ISSUE THREAD

**Issue by kcwu** [joto/osmoscope#15]
When mouse is moving, vertical scrollbar repeated appears and disappears. This makes the whole map shift slightly repeated and looks flickering.

Please see the video to understand what I'm talking about.
https://drive.google.com/file/d/1aeF11M_5fJg_6AJGF_bZcCFPxTKLw2cgzQ/view?usp=sharing

I found this issue is related to the coordinates shown on center bottom --- If I set style "display: none" to the coordinates, this issue disappeared.

**Comment by joto** [comment]
Okay, I am seeing two issues here:

1. There should be no scollbars at all. I don't see them in Firefox on Linux. We have to figure out where they come from.
2. The `div` that contains the coordinates should be large enough to hold any coordinate pair. If it is not, we can make it bigger. You can try whether that helps (in `app.css` change the `.ol-mouse-position` `width`). This could be font-related. Maybe the font on my system is slightly smaller, so I don't see this effect.

**Comment by kcwu** [comment]
I don't have time to try yet. FYI, I'm using chrome browser on windows.

**Comment by kcwu** [comment]
oops, I just go to your site and found it works well. The flickering issue disappeared. Given there are no commits recent week, it's probably something wrong in chrome browser and got fixed.
