### ISSUE TITLE
Cannot open geojson URL

### ISSUE THREAD

**Issue by RobJN** [joto/osmoscope#16]
Good to have a new tool. Looks very promising so thank you for starting it. From the blog post I got the impression that I should be able to open the following geojson, but site does nothing with it. It may just be user error on my part.Thanks.

File: https://osm.mathmos.net/ghosts/lloyds-tsb/osm-objects.geojson

**Comment by joto** [comment]
No, that's a misunderstanding. You can not directly use GeoJSON URLs, you have to write a meta-data file (in JSON format) describing your layer which then points to the GeoJSON file. I have just added some documentation: https://github.com/joto/osmoscope/blob/master/doc/creating-layers.md

**Comment by RobJN** [comment]
Makes sense, thanks. That also explains where the stats in your example were coming from. :+1:
