### ISSUE TITLE
Overpass-like ID-format for features?

### ISSUE THREAD

**Issue by hbruch** [joto/osmoscope#21]
While Overpass does not yet provide a geojson output format, it allows [exporting a result in GeoJSON](https://wiki.openstreetmap.org/wiki/Overpass_turbo/GeoJSON) via osmtogeojson.

The id format they use is id/@id with a value of "<type>/<id>". 

As generating osmoscope layers from overpass queries could become a common usecase, it would make sense build upon their formatting IMHO.

**Comment by joto** [comment]
Osmoscope shouldn't really care how IDs looks like as long as they are unique. I am not sure what OpenLayers supports here, but I suspect that it will work fine with the IDs generated by Overpass. Do you have a specific problem where those IDs currently don't work?

**Comment by hbruch** [comment]
Not really a problem. If Ids in Overpass format are supported by Osmoscope (in the sense that links to openstreetmap.org and the editors are auto-generated correctly), you could store overpass results directly as Osmoscope layer without post-processing. For e.g. the [Stations without P&R parking layer](https://mitfahren-bw.de/osmoscope/layers/layer_StationsWithoutPandR.json), I had to replace  `"@id"="node/` with `"node_id"="`. Not having to would make Osmoscope layer creation a snap.

**Comment by joto** [comment]
Ah, okay. That shouldn't be too difficult. We can have some magic that first checks for `node/way/relation_id` and, if that doesn't exist, tries `@id=XNNN` and `id=XNNN` with `X` being `n` or `node/` and `NNN` some number etc. We could have something in the layer description that tells us what's what, but it is probably easier to just add some magic.

We have to differentiate though between the `id` field and the `id` or `@id` property. Maybe we have to check both.

Vector tiles (at least in version 2) only have numeric IDs, so in that case we only have to check the properties.

If you want to try this out and send a PR, that would be great!

**Comment by hbruch** [comment]
I'll give it a try. 

Where is the "`X` being `n`" notation used? And do you know, what tippecanoe would transform a alpha-numeric id into?

**Comment by joto** [comment]
I use that notation myself sometimes. It is used in Osmium for instance. Just the shortest way of doing IDs I could think of. But we can always add that later.

Tippecanoe has several options for handling IDs. I haven't tried what it will do with the different options when it encounteres non-numeric IDs, but you can always use `--generate-ids` to generate correct unique numeric IDs.
