### ISSUE TITLE
https://osmoscope.openstreetmap.de/ -> wrong target

### ISSUE THREAD

**Issue by pathmapper** [joto/osmoscope#30]
https://osmoscope.openstreetmap.de/ is pointing to a different site:

![Auswahl_146](https://user-images.githubusercontent.com/20856381/54875821-07d9df00-4e06-11e9-9344-e12d091c2642.png)

![Auswahl_145](https://user-images.githubusercontent.com/20856381/54875825-0e685680-4e06-11e9-8cd0-f60da63654cc.png)

**Comment by joto** [comment]
Ups. Da hab ich nicht aufgepasst. Tut jetzt. Allerdings tun die Default-Layer unter https nicht (nur http). Da brauch ich aber mal etwas länger, das zu fixen.
